"use client";

import { Megaphone, Send, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { supabaseBrowser } from "@/lib/supabase-browser";
import type { TeamAnnouncement } from "@/lib/announcements/announcement-types";

const empty = { title: "", body: "", priority: "normal", audience: "families", link_label: "", link_url: "", publish_at: "", expires_at: "", status: "published" };
export default function AnnouncementManager() {
  const [form, setForm] = useState(empty), [items, setItems] = useState<TeamAnnouncement[]>([]), [status, setStatus] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { void load(); }, []);
  async function token() { return (await supabaseBrowser.auth.getSession()).data.session?.access_token ?? ""; }
  async function load() { const { data } = await supabaseBrowser.from("team_announcements").select("*").order("created_at", { ascending: false }).limit(100); setItems((data ?? []) as TeamAnnouncement[]); }
  async function save(event: React.FormEvent) {
    event.preventDefault(); setSaving(true); setStatus("");
    const response = await fetch("/api/announcements", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${await token()}` }, body: JSON.stringify(form) });
    const result = await response.json(); setStatus(response.ok ? form.status === "published" ? "Announcement published." : "Draft saved." : result.error);
    if (response.ok) { setForm(empty); await load(); } setSaving(false);
  }
  async function change(id: string, next: "draft" | "published") { await fetch(`/api/announcements/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${await token()}` }, body: JSON.stringify({ status: next }) }); await load(); }
  async function remove(id: string) { if (!confirm("Delete this announcement?")) return; await fetch(`/api/announcements/${id}`, { method: "DELETE", headers: { Authorization: `Bearer ${await token()}` } }); await load(); }
  return <div className="mx-auto max-w-5xl"><p className="text-xs font-black uppercase tracking-widest text-[#D7193F]">501 Elite OS</p><h1 className="mt-2 text-3xl font-black">Team announcements</h1><p className="mt-1 text-sm text-slate-500">Publish once. Reach every subscribed family.</p>
    <form onSubmit={save} className="mt-6 grid gap-3 rounded-3xl border bg-white p-5 shadow-sm sm:grid-cols-2"><input required maxLength={120} placeholder="Announcement title" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} className="rounded-xl border p-3 sm:col-span-2"/><textarea required maxLength={2000} rows={5} placeholder="What does the team need to know?" value={form.body} onChange={e => setForm({ ...form, body: e.target.value })} className="rounded-xl border p-3 sm:col-span-2"/><select value={form.priority} onChange={e => setForm({ ...form, priority: e.target.value })} className="rounded-xl border p-3"><option value="normal">Normal priority</option><option value="important">Important</option><option value="urgent">Urgent</option></select><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })} className="rounded-xl border p-3"><option value="published">Publish</option><option value="draft">Save draft</option></select><label className="text-sm font-bold">Publish date (optional)<input type="datetime-local" value={form.publish_at} onChange={e => setForm({ ...form, publish_at: e.target.value })} className="mt-1 w-full rounded-xl border p-3 font-normal"/></label><label className="text-sm font-bold">Expires (optional)<input type="datetime-local" value={form.expires_at} onChange={e => setForm({ ...form, expires_at: e.target.value })} className="mt-1 w-full rounded-xl border p-3 font-normal"/></label><input placeholder="Button label (optional)" value={form.link_label} onChange={e => setForm({ ...form, link_label: e.target.value })} className="rounded-xl border p-3"/><input type="url" placeholder="https://…" value={form.link_url} onChange={e => setForm({ ...form, link_url: e.target.value })} className="rounded-xl border p-3"/><button disabled={saving} className="flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#123E74] font-bold text-white sm:col-span-2"><Send className="h-5 w-5"/>{saving ? "Saving…" : form.status === "published" ? "Publish announcement" : "Save draft"}</button>{status ? <p className="text-sm sm:col-span-2">{status}</p> : null}</form>
    <div className="mt-6 space-y-3">{items.map(item => <article key={item.id} className="flex items-center justify-between gap-3 rounded-2xl border bg-white p-4"><div className="min-w-0"><div className="flex items-center gap-2"><Megaphone className="h-4 w-4 text-[#123E74]"/><b className="truncate">{item.title}</b></div><p className="mt-1 text-sm text-slate-500">{item.status} · {item.priority} · {new Date(item.publish_at).toLocaleString()}</p></div><div className="flex shrink-0"><button title={item.status === "published" ? "Move to drafts" : "Publish"} onClick={() => void change(item.id, item.status === "published" ? "draft" : "published")} className="min-h-11 rounded-full px-3 text-xs font-bold text-[#123E74]">{item.status === "published" ? "Unpublish" : "Publish"}</button><button title="Delete" onClick={() => void remove(item.id)} className="grid h-11 w-11 place-items-center text-red-600"><Trash2 className="h-5 w-5"/></button></div></article>)}</div>
  </div>;
}
