"use client";

import { CircleDollarSign, Pencil, Plus, ReceiptText, Trash2, UserPlus } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { supabaseBrowser } from "@/lib/supabase-browser";

type Family={id:string;family_name:string};type Account={id:string;family_id:string|null;account_number:number;display_name:string};type Charge={id:string;account_id:string;description:string;amount_cents:number;due_date:string|null;status:string;created_at:string};type Payment={id:string;account_id:string;amount_cents:number;method:string;reference:string;paid_at:string;status:string};
const rosterSurnames=["Dawson","Grimmett","Brown","Scott","Wiley","Frechette","Thomas","Chambers","George","Gillespie","Willingham","Mills","French"];
const normalizeAccountName=(value:string)=>value.toLocaleLowerCase().replace(/[^a-z0-9]/g,"").replace(/family$/,"");
const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(c/100);
export default function AccountingManager(){
 const[families,setFamilies]=useState<Family[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[charges,setCharges]=useState<Charge[]>([]),[payments,setPayments]=useState<Payment[]>([]),[selected,setSelected]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const[charge,setCharge]=useState({family_id:"",description:"2026–2027 Team Fee",amount:"",category:"team_fee",due_date:"",notes:""});
 const[payment,setPayment]=useState({account_id:"",amount:"",method:"cash",paid_at:"",reference:"",notes:""});
 async function token(){return(await supabaseBrowser.auth.getSession()).data.session?.access_token??""}async function load(){const[{data:f},{data:a},{data:c},{data:p}]=await Promise.all([supabaseBrowser.from("families").select("id,family_name").order("family_name"),supabaseBrowser.from("family_accounts").select("id,family_id,account_number,display_name").order("account_number"),supabaseBrowser.from("account_charges").select("*").order("created_at",{ascending:false}),supabaseBrowser.from("account_payments").select("*").order("paid_at",{ascending:false})]);setFamilies((f??[])as Family[]);setAccounts((a??[])as Account[]);setCharges((c??[])as Charge[]);setPayments((p??[])as Payment[])}async function reconcileRoster(){if(!confirm("Reconcile accounting accounts with the 13-player roster?\n\nMissing accounts will be created and accounting names will be corrected. Existing account numbers, charges, and payments will not change."))return;setBusy(true);const r=await fetch("/api/accounting/accounts/reconcile",{method:"POST",headers:{Authorization:`Bearer ${await token()}`}}),j=await r.json() as{error?:string;created?:string[];corrected?:string[]};setBusy(false);if(!r.ok){setMessage(j.error??"Roster accounts could not be reconciled.");return}setMessage(`Roster reconciliation complete. ${j.created?.length??0} created · ${j.corrected?.length??0} corrected.`);await load()}useEffect(()=>{queueMicrotask(()=>void load())},[]);
 const totals=useMemo(()=>{const billed=charges.filter(x=>x.status==="posted").reduce((s,x)=>s+x.amount_cents,0),paid=payments.filter(x=>x.status==="posted").reduce((s,x)=>s+x.amount_cents,0),overdue=charges.filter(x=>x.status==="posted"&&x.due_date&&new Date(x.due_date)<new Date()).reduce((s,x)=>s+x.amount_cents,0);return{billed,paid,balance:billed-paid,overdue:Math.max(0,overdue-paid)}},[charges,payments]);
 const rows=accounts.map(a=>{const billed=charges.filter(x=>x.account_id===a.id&&x.status==="posted").reduce((s,x)=>s+x.amount_cents,0),paid=payments.filter(x=>x.account_id===a.id&&x.status==="posted").reduce((s,x)=>s+x.amount_cents,0);return{...a,name:a.display_name||families.find(f=>f.id===a.family_id)?.family_name||"Unnamed family",billed,paid,balance:billed-paid}});
 const rosterAccountCount=rosterSurnames.filter(surname=>rows.some(account=>normalizeAccountName(account.name)===normalizeAccountName(surname))).length;
 async function post(url:string,body:object){setBusy(true);setMessage("");const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${await token()}`},body:JSON.stringify(body)}),j=await r.json();setMessage(r.ok?"Saved successfully.":j.error);if(r.ok)await load();setBusy(false);return r.ok}
 async function addAccount(){const name=prompt("New account name");if(name?.trim())await post("/api/accounting/accounts",{display_name:name})}
 async function editAccount(id:string,current:string){const name=prompt("Edit account name",current);if(!name?.trim()||name.trim()===current)return;const r=await fetch(`/api/accounting/accounts/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${await token()}`},body:JSON.stringify({display_name:name})});const j=await r.json();setMessage(r.ok?"Account name updated.":j.error);if(r.ok)await load()}
 async function deleteAccount(id:string,number:number,name:string){if(!confirm(`Delete account #${number} — ${name}?\n\nThis permanently removes its charges and payments. The family registration record will remain.`))return;const r=await fetch(`/api/accounting/accounts/${id}`,{method:"DELETE",headers:{Authorization:`Bearer ${await token()}`}}),j=await r.json();setMessage(r.ok?"Account deleted.":j.error);if(r.ok)await load()}
 return <div className="mx-auto max-w-6xl"><p className="text-xs font-black uppercase tracking-widest text-[#D7193F]">501 Elite OS</p><h1 className="mt-2 text-3xl font-black text-[#071D39]">Team accounting</h1><p className="mt-1 text-sm text-slate-500">Family fees, payments, balances, and account records.</p>
 <div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Billed",totals.billed],["Collected",totals.paid],["Outstanding",totals.balance],["Overdue",totals.overdue]].map(([l,v])=><div key={String(l)} className="rounded-2xl bg-[#071D39] p-4 text-white"><small className="text-blue-200">{String(l)}</small><b className="mt-2 block text-xl">{money(Number(v))}</b></div>)}</div>
 <div className="mt-6 grid gap-5 lg:grid-cols-2"><form onSubmit={async e=>{e.preventDefault();if(await post("/api/accounting/charges",charge))setCharge({...charge,amount:"",notes:""})}} className="grid gap-3 rounded-3xl border bg-white p-5"><h2 className="flex items-center gap-2 text-lg font-black"><Plus className="h-5 w-5"/>Add fee or charge</h2><select value={charge.family_id} onChange={e=>setCharge({...charge,family_id:e.target.value})} className="rounded-xl border p-3"><option value="">All family accounts</option>{families.map(f=><option key={f.id} value={f.id}>{f.family_name||"Unnamed family"}</option>)}</select><input required value={charge.description} onChange={e=>setCharge({...charge,description:e.target.value})} placeholder="Description" className="rounded-xl border p-3"/><div className="grid grid-cols-2 gap-3"><input required min="0.01" step="0.01" type="number" value={charge.amount} onChange={e=>setCharge({...charge,amount:e.target.value})} placeholder="Amount" className="rounded-xl border p-3"/><select value={charge.category} onChange={e=>setCharge({...charge,category:e.target.value})} className="rounded-xl border p-3"><option value="team_fee">Team fee</option><option value="uniform">Uniform</option><option value="tournament">Tournament</option><option value="equipment">Equipment</option><option value="fundraising">Fundraising</option><option value="other">Other</option></select></div><label className="text-sm font-bold">Due date<input type="date" value={charge.due_date} onChange={e=>setCharge({...charge,due_date:e.target.value})} className="mt-1 w-full rounded-xl border p-3 font-normal"/></label><textarea value={charge.notes} onChange={e=>setCharge({...charge,notes:e.target.value})} placeholder="Internal notes" className="rounded-xl border p-3"/><button disabled={busy} className="min-h-12 rounded-full bg-[#123E74] font-bold text-white">Add charge</button></form>
 <form onSubmit={async e=>{e.preventDefault();if(await post("/api/accounting/payments",payment))setPayment({...payment,amount:"",reference:"",notes:""})}} className="grid gap-3 rounded-3xl border bg-white p-5"><h2 className="flex items-center gap-2 text-lg font-black"><ReceiptText className="h-5 w-5"/>Record payment</h2><select required value={payment.account_id} onChange={e=>setPayment({...payment,account_id:e.target.value})} className="rounded-xl border p-3"><option value="">Select family account</option>{rows.map(a=><option key={a.id} value={a.id}>#{a.account_number} · {a.name} · {money(a.balance)}</option>)}</select><div className="grid grid-cols-2 gap-3"><input required min="0.01" step="0.01" type="number" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})} placeholder="Amount" className="rounded-xl border p-3"/><select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})} className="rounded-xl border p-3"><option value="cash">Cash</option><option value="check">Check</option><option value="venmo">Venmo</option><option value="cash_app">Cash App</option><option value="paypal">PayPal</option><option value="card">Card</option><option value="other">Other</option></select></div><label className="text-sm font-bold">Payment date<input type="datetime-local" value={payment.paid_at} onChange={e=>setPayment({...payment,paid_at:e.target.value})} className="mt-1 w-full rounded-xl border p-3 font-normal"/></label><input value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})} placeholder="Check number or transaction reference" className="rounded-xl border p-3"/><textarea value={payment.notes} onChange={e=>setPayment({...payment,notes:e.target.value})} placeholder="Internal notes" className="rounded-xl border p-3"/><button disabled={busy} className="min-h-12 rounded-full bg-[#D7193F] font-bold text-white">Record payment</button></form></div>{message?<p className="mt-4 rounded-xl bg-blue-50 p-3 text-sm text-[#123E74]">{message}</p>:null}
 <div className="mt-7"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="flex items-center gap-2 text-xl font-black"><CircleDollarSign className="h-5 w-5"/>Family accounts</h2><p className={`mt-1 text-sm font-bold ${rosterAccountCount===rosterSurnames.length?"text-emerald-700":"text-amber-700"}`}>Roster accounts: {rosterAccountCount}/{rosterSurnames.length}</p></div><div className="flex gap-2"><button disabled={busy} onClick={()=>void reconcileRoster()} className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#123E74] bg-white px-4 text-sm font-bold text-[#123E74] disabled:opacity-50">Reconcile roster</button><button onClick={()=>void addAccount()} className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#123E74] px-4 text-sm font-bold text-white"><UserPlus className="h-4 w-4"/>Add account</button></div></div><div className="mt-3 space-y-3">{rows.map(a=><article key={a.id} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-start gap-2"><button onClick={()=>setSelected(selected===a.id?"":a.id)} className="min-w-0 flex-1 text-left"><div className="flex items-center justify-between gap-3"><div><b>#{a.account_number} · {a.name}</b><p className="text-sm text-slate-500">Billed {money(a.billed)} · Paid {money(a.paid)}</p></div><b className={a.balance>0?"text-[#D7193F]":"text-emerald-600"}>{money(a.balance)}</b></div></button><button title="Edit account" onClick={()=>void editAccount(a.id,a.name)} className="grid h-11 w-11 shrink-0 place-items-center rounded-full text-[#123E74]"><Pencil className="h-4 w-4"/></button><button title="Delete account" onClick={()=>void deleteAccount(a.id,a.account_number,a.name)} className="grid h-11 w-11 shrink-0 place-items-center rounded-full text-red-600"><Trash2 className="h-4 w-4"/></button></div>{selected===a.id?<div className="mt-4 border-t pt-3 text-sm">{charges.filter(x=>x.account_id===a.id).map(x=><p key={x.id} className="py-1">Charge · {x.description} · {money(x.amount_cents)}</p>)}{payments.filter(x=>x.account_id===a.id).map(x=><p key={x.id} className="py-1 text-emerald-700">Payment · {x.method.replace("_"," ")} · {money(x.amount_cents)}{x.reference?` · ${x.reference}`:""}</p>)}</div>:null}</article>)}</div></div></div>
}
