import Link from "next/link";
import { ArrowRight, CalendarDays, FileText, IdCard, Users } from "lucide-react";
import type { FamilyDashboardData } from "@/lib/family/family-dashboard-service";
import InstallAppCard from "./InstallAppCard";
const steps=["parent","family","player","emergency","medical","uniform","review"];
export default function FamilyHome({data}:{data:FamilyDashboardData}){
 const r=data.registration;
 const href=!r?"/registration/parent":r.status==="draft"?`/registration/${steps[Math.min(Math.max(r.currentStep-1,0),6)]}`:r.releaseCount<6?"/registration/releases":r.documentStatus==="missing"||r.documentStatus==="rejected"?"/registration/documents":"/registration/success";
 const label=!r?"Start registration":r.status==="draft"?"Continue registration":r.releaseCount<6?"Sign releases":r.documentStatus==="missing"?"Add birth certificate":"Registration complete";
 return <div><InstallAppCard/><p className="text-xs font-black uppercase tracking-widest text-[#D7193F]">{data.family?.name||"501 Elite family"}</p><h1 className="mt-2 text-3xl font-black text-[#071D39]">{data.profile.firstName?`Hi, ${data.profile.firstName}.`:"Welcome home."}</h1><p className="text-sm text-slate-500">Everything your family needs, right here.</p>
 {data.nextEvent?<Link href="/dashboard/schedule" className="mt-5 block rounded-3xl border bg-white p-5 shadow-sm"><small className="font-black uppercase tracking-widest text-[#D7193F]">Next up</small><h2 className="mt-2 text-xl font-black text-[#071D39]">{data.nextEvent.title}</h2><p className="mt-1 text-sm text-slate-600">{new Date(data.nextEvent.starts_at).toLocaleString("en-US",{weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}{data.nextEvent.location_name?` · ${data.nextEvent.location_name}`:""}</p></Link>:null}
 <Link href={href} className="mt-5 block rounded-3xl bg-gradient-to-br from-[#123E74] to-[#071D39] p-5 text-white"><small className="font-black uppercase tracking-widest text-blue-200">Registration status</small><h2 className="mt-2 text-xl font-bold">{label}</h2><p className="mt-1 text-sm text-blue-100">{r?`Season ${r.season} · ${r.status}`:"Create your player registration"}</p><ArrowRight className="ml-auto"/></Link>
 <h2 className="mb-3 mt-6 text-lg font-black">Quick actions</h2><div className="grid grid-cols-2 gap-3">{[["Schedule","/dashboard/schedule",CalendarDays],["Registration",href,IdCard],["Documents","/registration/documents",FileText],["My players","/dashboard/team",Users]].map(([l,h,I])=><Link key={String(l)} href={String(h)} className="flex min-h-28 flex-col justify-between rounded-2xl border bg-white p-4 shadow-sm"><I className="h-6 w-6 text-[#123E74]"/><b className="text-sm">{String(l)}</b></Link>)}</div>
 <h2 className="mb-3 mt-6 text-lg font-black">Your players</h2><div className="space-y-3">{data.players.map(x=><div key={x.id} className="rounded-2xl border bg-white p-4"><b>{x.preferredName||x.firstName} {x.lastName}</b><p className="text-sm text-slate-500">{x.grade?`${x.grade} grade`:"501 Elite player"}</p></div>)}</div></div>;
}
